<ul>
<li>Jak się zachowuje blank</li>

<li>Oszacować jaka jest odpowiedź sprzętu dla blanku w stosunku do średniej uzyskanych dla danych</li>

<li>Jak zachowują się próbki quality control</li>
</ul>

<h4>Import bibliotek</h4>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")

<h4>Wczytanie plików do analizy</h4>

In [2]:
qual_df1 = pd.read_excel("Metabolomika_Quality1.xlsx")
qual_df2 = pd.read_excel("Metabolomika_Quality2.xlsx")

<h4>Wyświetlenie części danych, wymiarów i krótko statystyk</h4>

In [3]:
qual_df1.head()

,Id,Group,M1,M2,M3,M4,M5,M6,M7,M8,...,M1190,M1191,M1192,M1193,M1194,M1195,M1196,M1197,M1198,M1199
0,F_HM1,F_Mutacja2,5.957279e+10,3.010289e+09,2.419360e+09,3.475658e+10,1.095557e+10,1.820461e+10,4.352209e+10,4.040102e+10,...,1.174422e+07,4.440530e+05,4.251011e+06,6.055340e+06,6.393848e+07,1.182480e+06,1.008544e+06,5.246082e+07,1.662718e+07,6.161780e+07
1,F_HM2,F_Mutacja2,3.261696e+10,1.202132e+09,1.028235e+09,1.985418e+10,5.097178e+09,8.471569e+09,2.088800e+10,4.951979e+09,...,7.158440e+06,3.746337e+05,1.081334e+08,1.857941e+06,2.976110e+07,7.085763e+05,3.915174e+06,3.126943e+07,7.024416e+05,3.162653e+07
2,F_HM3,F_Mutacja2,4.710931e+10,4.235189e+09,3.731590e+09,2.954711e+10,1.389437e+10,1.848030e+10,2.629877e+10,3.185078e+10,...,3.795373e+06,4.153529e+05,1.941860e+06,2.917358e+06,1.992001e+07,1.108783e+06,1.342495e+07,2.241231e+07,1.727761e+07,2.464116e+07
3,F_HM4,F_Mutacja2,4.105237e+10,5.480769e+10,6.266317e+10,2.751340e+10,5.997451e+10,4.372237e+10,2.382849e+10,4.136071e+10,...,3.287727e+07,3.002645e+07,5.251650e+06,1.925589e+06,3.559016e+07,4.243901e+07,3.681430e+07,3.942579e+07,2.550144e+07,5.896691e+07
4,F_HM5,F_Mutacja2,8.245476e+10,4.795234e+09,3.809418e+09,5.674860e+10,1.153197e+10,1.989166e+10,3.385781e+10,4.839285e+10,...,7.356279e+06,5.233009e+05,1.234122e+07,3.854842e+05,4.859317e+07,1.316606e+06,2.892370e+07,3.719735e+07,1.398120e+07,4.346311e+07

In [4]:
qual_df1.shape

(220, 1201)

In [29]:
qual_df1['Group'].value_counts()

Group
Blank         38
F_Kontrola    29
M_Kontrola    28
F_Mutacja1    28
M_Mutacja1    27
F_Mutacja2    27
QC            22
M_Mutacja2    21
Name: count, dtype: int64

In [15]:
qual_df2.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1190,Unnamed: 1191,Unnamed: 1192,Unnamed: 1193,Unnamed: 1194,Unnamed: 1195,Unnamed: 1196,Unnamed: 1197,Unnamed: 1198,Unnamed: 1199
0,NaN,Blank1,Blank2,Blank3,Blank4,Blank5,Blank6,Blank7,Blank8,Blank9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M1,96050301.189067,91071913.798473,130188374.515884,144525722.751977,107318018.292966,266197041.995283,110669570.744356,49100228.798503,191160394.600623,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M2,5190022905.80748,2427643936.48469,13622766045.204599,4785712597.17914,4248665290.76787,31901453283.248901,22958908.704539,1800509689.27854,27509589706.560001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,M3,37227156.982608,30727357.671339,41898495.55181,47658756.073795,37787753.868623,48359048.381559,44060174.034634,53009619.735754,50617795.896764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,M4,49812971.982919,17933984.303862,9379937.976367,5683682578.80977,17901062.023144,151598337.788689,3736066.816465,7414297.651831,2384338.710906,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
qual_df2.shape

(1348, 1200)

In [36]:
qual_df2.iloc[0,:].unique()

array([nan, 'Blank1', 'Blank2', 'Blank3', 'Blank4', 'Blank5', 'Blank6',
       'Blank7', 'Blank8', 'Blank9', 'Blank10', 'QC1', 'QC2', 'QC3',
       'QC4', 'QC5', 'QC6', 'QC7', 'QC8', 'QC9', 'QC10', 'QC11', 'QC12',
       'QC13', 'QC14', 'QC15', 'QC16', 'QC17', 'QC18', 'F_HT1', 'F_HT2',
       'F_HT3', 'F_HT4', 'F_HT5', 'F_HT6', 'F_Kontrola1', 'F_Kontrola2',
       'F_Kontrola3', 'F_Kontrola4', 'F_Kontrola5', 'F_HM1', 'F_HM2',
       'F_HM3', 'F_HM4', 'F_HM5', 'F_HM6', 'F_HT7', 'F_HT8', 'F_HT9',
       'F_HT10', 'F_HT11', 'F_HT12', 'F_HT13', 'F_HT14', 'F_HT15',
       'F_Kontrola6', 'F_Kontrola7', 'F_Kontrola8', 'F_Kontrola9',
       'F_Kontrola10', 'F_Kontrola11', 'F_Kontrola12', 'F_HM7', 'F_HM8',
       'F_HM9', 'F_HM10', 'F_HM11', 'F_HM12', 'F_HM13', 'F_HM14',
       'F_HT16', 'F_HT17', 'F_HT18', 'F_HT19', 'F_HT20', 'F_HT21',
       'F_HT22', 'F_Kontrola13', 'F_Kontrola14', 'F_Kontrola15',
       'F_Kontrola16', 'F_Kontrola17', 'F_Kontrola18', 'F_Kontrola19',
       'F_Kontrola20', 'F_Kontrola21', 'M_HM1', 'M_HM2', 'M_HM3', 'M_HM4',
       'M_HM5', 'M_HM6', 'M_HM7', 'M_HM8', 'M_HM9', 'M_HT1', 'M_HT2',
       'M_HT3', 'M_HT4', 'M_HT5', 'M_Kontrola1', 'M_Kontrola2',
       'M_Kontrola3', 'M_Kontrola4', 'M_Kontrola5', 'M_Kontrola6',
       'M_Kontrola7', 'M_HM10', 'M_HM11', 'M_HM12', 'M_HM13', 'M_HT6',
       'M_HT7', 'M_HT8', 'M_HT9', 'M_HT10', 'M_HT11', 'M_HT12', 'M_HT13',
       'M_HT14', 'M_HT15', 'M_Kontrola8', 'M_Kontrola9', 'M_Kontrola10',
       'M_Kontrola11', 'M_HM14', 'M_HM15', 'M_HM16', 'M_HM17', 'M_HM18',
       'M_HT16', 'M_HT17', 'M_HT18', 'M_HT19', 'M_HT20', 'M_HT21',
       'M_HT22', 'M_HT23', 'M_HT24', 'M_HT25', 'M_HT26', 'M_Kontrola12',
       'M_Kontrola13', 'M_Kontrola14', 'M_Kontrola15', 'M_Kontrola16',
       'M_Kontrola17'], dtype=object)

In [32]:
qual_df2.iloc[0,:].nunique()

146

<h4>Macierz korelacji kowariancji</h4>

In [41]:
qual_df1.iloc[:,2:].corr()

,M1,M2,M3,M4,M5,M6,M7,M8,M9,M10,...,M1190,M1191,M1192,M1193,M1194,M1195,M1196,M1197,M1198,M1199
M1,1.000000,0.064955,0.059622,0.964600,0.288996,0.481302,0.868063,0.849478,0.862708,0.874320,...,0.315251,0.500696,0.268415,0.051445,0.700576,0.473454,0.384737,0.745881,0.525018,0.648818
M2,0.064955,1.000000,0.974089,0.189647,0.840113,0.693290,0.063379,0.296255,0.355406,0.260178,...,0.535527,0.294935,0.019234,0.050936,0.195364,0.297831,0.418121,0.255527,0.166263,0.339239
M3,0.059622,0.974089,1.000000,0.185153,0.860124,0.735458,0.056283,0.285188,0.341875,0.241550,...,0.458194,0.284006,0.033590,0.045549,0.184599,0.287200,0.373203,0.235441,0.156105,0.338538
M4,0.964600,0.189647,0.185153,1.000000,0.397843,0.580156,0.786062,0.828377,0.883263,0.888731,...,0.383901,0.576450,0.256827,0.052319,0.713831,0.549995,0.482387,0.778297,0.578145,0.679153
M5,0.288996,0.840113,0.860124,0.397843,1.000000,0.917842,0.286178,0.500051,0.535742,0.439231,...,0.343646,0.363930,0.068045,0.044801,0.344462,0.360664,0.421909,0.382363,0.267737,0.459331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
M1195,0.473454,0.297831,0.287200,0.549995,0.360664,0.410401,0.332292,0.370257,0.543226,0.556234,...,0.402466,0.922237,0.161755,0.189204,0.595494,1.000000,0.400363,0.650706,0.433346,0.638544
M1196,0.384737,0.418121,0.373203,0.482387,0.421909,0.390552,0.169272,0.293503,0.487545,0.412796,...,0.704658,0.434398,0.225061,0.193503,0.289987,0.400363,1.000000,0.414500,0.710735,0.499661
M1197,0.745881,0.255527,0.235441,0.778297,0.382363,0.479465,0.655085,0.686857,0.799756,0.765189,...,0.415414,0.646881,0.274807,0.168973,0.815946,0.650706,0.414500,1.000000,0.464640,0.709946
M1198,0.525018,0.166263,0.156105,0.578145,0.267737,0.359879,0.295595,0.417195,0.540468,0.576556,...,0.539716,0.418657,0.214752,0.102364,0.368667,0.433346,0.710735,0.464640,1.000000,0.379456
M1199,0.648818,0.339239,0.338538,0.679153,0.459331,0.500282,0.604252,0.578789,0.750556,0.639324,...,0.412699,0.717238,0.383353,0.323547,0.666022,0.638544,0.499661,0.709946,0.379456,1.000000

Widać, że niektóre wartości są wysoko skorelowane

In [42]:
qual_df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1190,Unnamed: 1191,Unnamed: 1192,Unnamed: 1193,Unnamed: 1194,Unnamed: 1195,Unnamed: 1196,Unnamed: 1197,Unnamed: 1198,Unnamed: 1199
0,NaN,Blank1,Blank2,Blank3,Blank4,Blank5,Blank6,Blank7,Blank8,Blank9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M1,96050301.189067,91071913.798473,130188374.515884,144525722.751977,107318018.292966,266197041.995283,110669570.744356,49100228.798503,191160394.600623,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M2,5190022905.80748,2427643936.48469,13622766045.204599,4785712597.17914,4248665290.76787,31901453283.248901,22958908.704539,1800509689.27854,27509589706.560001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,M3,37227156.982608,30727357.671339,41898495.55181,47658756.073795,37787753.868623,48359048.381559,44060174.034634,53009619.735754,50617795.896764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,M4,49812971.982919,17933984.303862,9379937.976367,5683682578.80977,17901062.023144,151598337.788689,3736066.816465,7414297.651831,2384338.710906,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1343,M_Kontrola13,559565528.757725,44558982677.888702,4957863078.23143,1932111248.3341,2547542967.9649,155501864.064447,7904060725.95108,155690733.934866,5630441409.87046,...,558956.843281,932945.43913,450215.188536,846962.647713,954160.850928,255435.508993,397888.406607,548229.283209,309226.127234,227960.284482
1344,M_Kontrola14,935276573.118361,51308306646.874802,4619694118.58622,1646787506.51897,2014284731.41428,116282306.64945,9749146386.09749,117715403.508262,7576869911.87926,...,391143.257235,596982.965347,429134.060582,960448.619316,822754.857334,378944.12012,319710.672297,535639.9506,412730.062661,321337.137541
1345,M_Kontrola15,619220488.642601,49904584548.010902,3242918197.52239,2060255868.50729,2846327635.52422,239892293.339139,8262098364.59634,240838563.990626,7330104139.39339,...,319011.944256,1514492.826684,1647573.673579,1121697.053547,809579.283938,404891.341218,451720.325676,1054918.826685,515908.779667,233066.731353
1346,M_Kontrola16,166814096.867582,39042682551.636703,1194294766.02071,20580646.517929,122377543.82241,243231773.831295,10818199104.397301,477959067.47707,6466235552.11453,...,209544.693453,250176.535644,238082.310323,802625.351075,617666.156874,99772.453319,179479.290333,138902.071507,132065.111788,147286.294365
1347,M_Kontrola17,1797891761.49983,79370582121.382294,820335082.75137,2987636191.43315,1523969285.06651,188508653.487067,8663503063.592501,185345678.041008,7136993480.37232,...,538870.183986,1628996.98135,1160497.699874,1789615.294464,870738.995387,292076.089856,456586.389306,1283088.459601,486189.016709,362734.587001